### PR TITLE
[noticket] refactor: Remove usage of eval

### PR DESCRIPTION
**Pull request by aragon999**
No need for `eval` here :-)

### CODE REVIEW

**Comment by kleinmann** [comment]
@aragon999 Thank you for your contribution! Unfortunately, with your change, the content of the ignored tables is dumped erroneously. I usually check with `acl_user_role` in the resulting dump. This table has no content with the current `main` branch, but has content with your change.

Do you want to take another stab at it? 🙂

**Comment by aragon999** [comment]
@kleinmann thank you for your feedback, although I am not 100% sure what is happening, it seems that single quotes can lead to some strange behavior when using the array expansion.

Can you test it again? If it works I can also squash all commits.

**Comment by kleinmann** [comment]
@aragon999 That's looking great, thank you very much! No squashing needed 🙂

**Comment by aragon999** [comment]
Very good :-) thank you for the fast merge.

**Pull request merged**
